#!/bin/csh
# snapResource
rTracker.py          -t 100 -b Dennis -g Dorothy -R    ~/Dropbox/Photos/myResources ~/myResource.all
rTracker.py -f art.  -t 100 -b Dennis -g Dorothy -R    ~/Dropbox/Photos/myResources ~/myResource.art
rTracker.py -f auto. -t 100 -b Dennis -g Dorothy -R    ~/Dropbox/Photos/myResources ~/myResource.auto
rTracker.py          -t 120 -b Dennis -g Dorothy -s 5  ~/Dropbox/Photos/myResources ~/myResource.summary
