int LIB_SOCKET_client_setup (char *host_name,char *service_name,char *family_name);
int LIB_SOCKET_server_setup (char *host_name,char *service_name,char *family_name);
int LIB_SOCKET_server_accept (int socket_fd);
int LIB_SOCKET_disconnect (int socket_fd);
int LIB_SOCKET_read (int socket_fd,char *ptr,int nbytes);
int LIB_SOCKET_write (int socket_fd,char *ptr,int nbytes);
int LIB_DATAGRAM_client_setup (char *host_name,char *service_name,char *family_name);
int LIB_DATAGRAM_server_setup (char *host_name,char *service_name,char *family_name);
int LIB_DATAGRAM_write_setup ();
int LIB_DATAGRAM_read_setup (char *host_name,char *service_name);
int LIB_DATAGRAM_disconnect (int socket_fd);
int LIB_DATAGRAM_read(struct sockaddr_in * from,int socket_fd,char *ptr,int nbytes);
int LIB_DATAGRAM_write(char *host_name,char *service_name,int socket_fd,char *ptr,int nbytes);
int LIB_DATAGRAM_write_to(struct sockaddr_in * to,int socket_fd,char *ptr,int nbytes);
int LIB_SOCK_UTIL_readn (int fd,char *ptr,int nbytes);
int LIB_SOCK_UTIL_writen (int fd,char *ptr,int nbytes);
int LIB_SOCK_UTIL_readline (int fd,char *ptr,int maxlen);
void LIB_SOCK_UTIL_str_echo (int sockfd);
void LIB_SOCK_UTIL_str_cli (FILE *fp,int sockfd);
void LIB_SOCK_UTIL_dg_echo (int sockfd,struct sockaddr *pcli_addr,int maxclilen);
void LIB_SOCK_UTIL_dg_cli (FILE *fp,int sockfd,struct sockaddr *pserv_addr,int servlen);
